<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="1.900" timestamp="2024-01-31T15:41:34.587191" hostname="DESKTOP-H05ROVE"><testcase classname="" name="tests.model.test_model" time="0.000"><error message="collection failure">..\..\..\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1050: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1027: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1006: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:688: in _load_unlocked
    ???
..\..\..\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\assertion\rewrite.py:170: in exec_module
    exec(co, module.__dict__)
C:\Users\maros\Downloads\challenge_MLE\tests\model\test_model.py:6: in &lt;module&gt;
    ???
challenge\model.py:7: in &lt;module&gt;
    class DelayModel:
challenge\model.py:63: in DelayModel
    ) -&gt; Union(Tuple[pd.DataFrame, pd.DataFrame], pd.DataFrame):
..\..\..\AppData\Local\Programs\Python\Python310\lib\typing.py:387: in __call__
    raise TypeError(f"Cannot instantiate {self!r}")
E   TypeError: Cannot instantiate typing.Union</error></testcase></testsuite></testsuites>